version: '3'
services:
  pypicloud:
    command: sh -c '/wait-for -t 30 mysql:3306 -- uwsgi --die-on-term /etc/pypicloud/config.ini'
    depends_on:
      - mysql
    # image: stevearc/pypicloud
    image: mcchae/pypicloud:1.1.7
    ports:
      - "8080:8080"
    volumes:
      - ./packages:/var/lib/pypicloud/packages
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: pypi
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    user: "1000"
    volumes:
      - ./datadir:/var/lib/mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE