version: '3'
services:
  pypicloud:
    command: sh -c '/wait-for -t 30 mysql:3306 -- uwsgi --die-on-term /etc/pypicloud/config.ini'
    depends_on:
      - mysql
    # image: stevearc/pypicloud
    image: pypicloud:1.1.7
    ports:
      - "8080:8080"
    volumes:
      - ./config-mysql.ini:/etc/pypicloud/config.ini:ro
      - ./wait-for:/wait-for:ro
      - /root/mywork/docker-pypicloud/packages:/var/lib/pypicloud/packages
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: pypi
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - /root/mywork/docker-pypicloud/datadir:/var/lib/mysql
